### ISSUE TITLE
[Lab0] Setup SD card 

### ISSUE THREAD

**Issue by ianchen-tw** [GrassLab/NYCU_Operating_System_Capstone#1]
@t0037799 助教您好

### Unclear requirement or statement in documentation

**URL:** https://grasslab.github.io/NYCU_Operating_System_Capstone/labs/lab0.html

**Confused sentence**

> ## Flash Bootable Image to SD Card
>  There are two ways to do it.
> 1. We already prepared a bootable image. You can use the following command to flash it to your SD card.
> 2. ...
... 
> ### Interact with Rpi3
> Use the provided kernel8.img and connect TX, RX, GND to the corresponding pins on rpi3. After power on, you can read and write data from /dev/ttyUSB0 (Linux). You can use putty or screen with baud rate 115200 to interact with your rpi3.

**Your understanding or question:**

**問題一**
 
這邊說有兩種方法可以設定 SD 卡，但在 `Interact with Rpi3` 中卻只提到 `Use the provided kernel8.img`。
雖然這樣的上下文敘述暗示，連結提供的 `kernel8.img` 跟第一點 bootable image(nctuos.img) 中的`kernel8.img` 是相同的，但我無法根據給予的敘述確定這件事 (雖然直接diff檔案應該就可以了)。

**問題二**

最後面有提到 **After power on, you can read and write data from /dev/ttyUSB0 (Linux)**，這邊並沒有明確說到

1. read/write 的方法
2. 如果使用提供的image正確開機後，期望會看到什麼結果

所以我想問文件上給予的 kernel 有提供什麼功能？以及我有辦法在不開始 Lab1 (interactive shell )的情況下，確認我設定的硬體(樹莓派+接線) 是正確的嗎？

**Comment by t0037799** [comment]
**問題一**
是相同的沒錯，已加入以下描述

> 1. If you use method 2 to set up your bootable image, you should download kernel8.img , and put it into your boot partition. It’s identical to the one in the provided bootable image.

**問題二**
只要用一般可以操作serial console的程式，如下以screen, putty以正確鮑率開啟檔案即可讀寫數據
`
screen /dev/ttyUSB0 115200
`

開機後不會有額外資訊，同學確認線路和image正常的方式為在serial console打字，應該要能夠看到你所打出來的內容

**問題三**
 所以我想問文件上給予的 kernel 有提供什麼功能？以及我有辦法在不開始 Lab1 (interactive shell )的情況下，確認我設定的硬體(樹莓派+接線) 是正確的嗎？

已加入以下描述
> In our provided bootable image, it contains a kernel image can echoes what you type through UART. You can use it to test if your Lab kits function well.

文件已經稍作更新，如果還是不清楚可以再提出，謝謝同學回報。

**Comment by ianchen-tw** [comment]
@t0037799 
助教謝謝，補上的內容對除錯有很大的幫助
