### ISSUE TITLE
[Lab5] Program code of thread

### ISSUE THREAD

**Issue by jinbaohong** [GrassLab/NYCU_Operating_System_Capstone#11]
I want to confirm my understanding of  the"program code" of a thread. "The program code" I mentioned here is the code which a thread is going to run. 

My understanding:
1. In require 1, the program code is directly from function.
For example, ```foo()``` is the program code in case of ```thread_create(foo);```. It is a function in our kernel image, so we can pass its address to ```thread_create()```.
2. In require 2, the program code is from initramfs.
For example, ```bin/hello``` is a machine code file in initramfs, and we have to load it as our program code.

Thanks.

**Comment by t0037799** [comment]
Yes.
