### ISSUE TITLE
[Lab6] Populate the root file system

### ISSUE THREAD

**Issue by jinbaohong** [GrassLab/NYCU_Operating_System_Capstone#13]
Hi,
I'm a bit confused of the meaning of "populate":
> Populate the root file system with initramfs using the VFS APIs and the tmpfs.

Does it mean that we have to reorganize the content of initramfs so that open/read/write/close can play with it?

thanks

**Comment by t0037799** [comment]
No, "populate" here means you need to extract the files from the initramfs(initramfs is read-only) to your rootfs(tmpfs)
