### ISSUE TITLE
[Lab3] elective 1: Memory Reservation Info Problem

### ISSUE THREAD

**Issue by jinbaohong** [GrassLab/NYCU_Operating_System_Capstone#8]
In lab3 elective 1, we have to know memory reservation information.
I'd tried to get the information from device tree's Memory Reservation Block. I expected it to store several blocks information (e.g. initramfs, cpio.), but it only tells one block (address=0, size=4096).
Is that normal?

**Comment by t0037799** [comment]
Yes, the bootloader may not tell you all memory block you need to reserve.
But your kernel can still get the base address and the size of initramfs, dtb, and itself from elsewhere.

Go back to elective1's requirements.
Your startup allocator provides the mechanism that someone can reserve memory blocks.
The detection of the preset reserved memory blocks doesn't need to be included in the startup allocator. 

Already add the following description to the documentation.
> Reserved memory block detection is not part of the startup allocator. You can either find a way to get those information or hard code it. Then call the startup allocator's API to reserve those regions. 

If you think it's clear now, please close the issue
