### ISSUE TITLE
[Lab4] elective 2: blocking or non-blocking

### ISSUE THREAD

**Issue by jinbaohong** [GrassLab/NYCU_Operating_System_Capstone#9]
In elective 2, we're going to implement a shell command, setTimeout. 
Is setTimeout supposed to block our shell for seconds?
Or return to user immediately?

Thanks.

**Comment by t0037799** [comment]
It's non-blocking.

Already added the following to the documentation.
> .. note::
    ``setTimeout`` is non-blocking. Users can set multiple timeouts. 
    The printing order is determined by the command executed time and the user specified SECONDS.
